name: build

on:
#  release:
#    types: [published]
  push:
    branches:
      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5

    
env:
  ROM_URL: https://bigota.d.miui.com/V12.5.3.0.QCPCNXM/olivelite_images_V12.5.3.0.QCPCNXM_20211105.0000.00_10.0_cn_11862639cb.tgz
  ROM_NAME: Generic
  BUILD_TYPE: ab
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initialization environment
         run: |
              sudo apt install git
              echo "BUILD_TIME=$(date +%s | md5sum | awk '{print substr($1,1,10)}')" >> $GITHUB_ENV
           
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/mi20210630/ErfanGSIs.git ErfanGSIs
         
       - name: Fix exit
         run: |
              sed -i 's/\|\| exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
              sed -i 's/exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
       
       - name: Setting up ErfanGSI requirements
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs
              mkdir ./output
              sudo bash ./setup.sh
              java -version
              pip3 install aligo
              
       - name: Download Stock Rom & Generate GSI
         run: |
             cd $GITHUB_WORKSPACE/ErfanGSIs
             sudo bash ./url2GSI.sh -c --$BUILD_TYPE $ROM_URL $ROM_NAME
       
       - name: Zip GSI  
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs/output
              zip -r GSI.zip ./*
              mkdir upload
              if [[ $(du -sb "GSI.zip" | awk '{print $1}') -gt 2097152000 ]];then
                  echo -e "split packaging..."
                  tar -cpzf - "GSI.zip" | split -d -b 1024m - "upload/GSI.zip"
              else
                  mv GSI.zip upload/
              fi
              ls "upload"                  
              
       - name: Upload GSI to release
         uses: ncipollo/release-action@v1.8.6
         with:
           artifacts: ${{ github.workspace }}/ErfanGSIs/output/upload/*
           tag: ErfanGSIs-${{ env.ROM_NAME }}-${{ env.BUILD_TYPE }}-${{ env.BUILD_TIME }}
           bodyFile: "${{ github.workspace }}/ErfanGSIs/output/info.txt"
           token: ${{ secrets.PAT }}
