name: ErfanGSIs-online

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
#  watch:
#    types: [started]
  workflow_dispatch
    
env:
  ROM_URL: https://firmware.meizu.com/Firmware/Flyme/meizu18S_Pro/9.3.0.0/cn/20220812160612/9ee2f23c/update.zip
  ROM_NAME: Generic
  BUILD_TYPE: ab
  TZ: Asia/Shanghai
  ARTIFACT_NAME: ErfanGSIs-test 

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq install git wget python3
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git ErfanGSIs
         
       - name: Fix exit
         run: |
              sed -i 's/\|\| exit 1//g' ErfanGSIs/url2GSI.sh
              sed -i 's/exit 1//g' ErfanGSIs/url2GSI.sh
       
       - name: Setting up ErfanGSI requirements
         run: |
              cd ErfanGSIs
              mkdir ./output
              sudo apt purge python3-minimal && sudo apt purge python3
              wget http://archive.ubuntu.com/ubuntu/pool/main/p/python3-defaults/python3-minimal_3.8.2-0ubuntu2_amd64.deb
              wget http://archive.ubuntu.com/ubuntu/pool/main/p/python3-defaults/python3_3.8.2-0ubuntu2_amd64.deb
              sudo dpkg -i python3-minimal_3.8.2-0ubuntu2_amd64.deb && sudo dpkg -i python3_3.8.2-0ubuntu2_amd64.deb
              sudo apt update && sudo apt install unace unrar zip unzip p7zip-full p7zip-rar sharutils rar uudeview mpack arj cabextract file-roller device-tree-compiler liblzma-dev python-pip brotli liblz4-tool gawk aria2
              sudo apt install python3-pip
              pip3 install backports.lzma protobuf pycrypto
              pip3 install protobuf==3.20.0
       
       - uses: actions/setup-python@v4
         with:
             python-version: '3.8.13' 
       - run: |
              cd  ErfanGSIs
              sudo bash ./url2GSI.sh -c --$BUILD_TYPE $ROM_URL $ROM_NAME
       
       - name: Zip GSI  
         run: |
              cd ErfanGSIs
              mkdir upload
              sudo apt-get install p7zip 
              7z a -t7z -r ./upload/test.7z ./output/*
       
       - name: Upload artifact
         uses: actions/upload-artifact@v3
         with:
           name: ${{ env.ARTIFACT_NAME }}
           path: |
                 "ErfanGSIs/output/*"
                 "ErfanGSIs/upload/test.7z*"
                 
       - name: Upload GSI to WeTransfer
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs/upload
              curl -sL https://git.io/file-transfer | sh
              ./transfer wet ./test.tar.gz

